SELECT RET.ITEM_ID, RET.ITEM_NAME, RET.RARITY
FROM ITEM_INFO AS I, ITEM_TREE AS T, ITEM_INFO AS RET
WHERE (I.ITEM_ID = T.PARENT_ITEM_ID) AND (I.RARITY = 'RARE') AND(RET.ITEM_ID = T.ITEM_ID)
ORDER BY RET.ITEM_ID DESC